apiVersion: v1
kind: ConfigMap
metadata:
  name: linquickrec-config
  namespace: linquickrec
data:
  KVWORKER_HOST: "141.61.84.245"
  KVWORKER_PORT: "31502"
  ETCD_ADDRESS: "141.61.84.245:2379"
  TTL_SECONDS: "5"
  PRECALC_RESULT_SIZE_MB: "8.5"
  PAYLOAD_SIZE_KB: "100"
  SCORING_DELAY_MS: "100"
  SUB_WORKER_COUNT: "10"
  TOP_K: "100"
  SUB_WORKER_TIMEOUT_MS: "5000"
  VLLM_PORT: "8000"
  VLLM_BASE_URL: "http://127.0.0.1:8000"
  VLLM_ENDPOINT: "/v1/chat/completions"
  MODEL_NAME: "/app/models/Qwen3-0.6B/"
  VLLM_TIMEOUT_MS: "100000"
  SKU_COUNT: "100"
  DISCOVERY_ADDR: "discovery-server:8100"
  FEATURE_SERVICE_ADDR: "feature-service:8003"
  RECALL_SERVICE_ADDR: "recall-service:8001"
  PRECALC_SERVICE_ADDR: "precalc-service:8004"
  RANK_SERVICE_ADDR: "rank-master-service:8005"
  SERVER_NUM_THREADS: "0"
  SERVER_IDLE_TIMEOUT_SEC: "-1"
  SERVER_MAX_CONCURRENCY: "0"
  DISCOVERY_CLIENT_TIMEOUT_MS: "5000"
  DISCOVERY_CLIENT_CONNECTION_TYPE: "single"
  DISCOVERY_CLIENT_MAX_RETRY: "2"
  DISCOVERY_CLIENT_CONNECT_TIMEOUT_MS: "-1"
  DISCOVERY_CLIENT_BACKUP_REQUEST_MS: "-1"
  DOWNSTREAM_CONNECTION_TYPE: "pooled"
  DOWNSTREAM_MAX_RETRY: "3"
  DOWNSTREAM_CONNECT_TIMEOUT_MS: "-1"
  FEATURE_BACKUP_REQUEST_MS: "-1"
  RECALL_BACKUP_REQUEST_MS: "-1"
  PRECALC_BACKUP_REQUEST_MS: "-1"
  RANK_BACKUP_REQUEST_MS: "-1"
  VLLM_CONNECTION_TYPE: "single"
  VLLM_MAX_RETRY: "3"
  VLLM_CONNECT_TIMEOUT_MS: "-1"
  VLLM_BACKUP_REQUEST_MS: "-1"
  SUB_WORKER_CONNECTION_TYPE: "pooled"
  SUB_WORKER_MAX_RETRY: "3"
  SUB_WORKER_CONNECT_TIMEOUT_MS: "-1"
  SUB_WORKER_BACKUP_REQUEST_MS: "-1"
  SUB_WORKER_PARALLELISM: "4"
